{{- if not .Values.secret.db.superuser.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.db.superuser" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secret.db.superuser }}
{{- if $value }}
{{- if or (eq (typeOf $value) "string") (eq (typeOf $value) "numeric") }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- end }}
  password_encoded: {{ .Values.secret.db.superuser.password | urlquery | b64enc }}
{{- end }}
